name: Clojure

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: lein do with-profile uberjar deps, cljfmt check
    - name: Install dependencies
      run: lein test
