---
name: Clojure
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: DeLaGuardo/setup-clojure@6d46099eae24853c33c0482f2bb54edf4f1a4c74 # 13.7.0
        with:
          lein: '2.12.0'
          clj-kondo: '2020.04.05'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Lint
        run: clj-kondo --lint .
      - name: Install dependencies, Run syntax conformance checks
        run: lein do with-profile uberjar deps, cljfmt check
      - name: Run tests
        run: lein coverage --junit --lcov
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@a9170d5795813c01ab4901ffb045b52bab4ab09d # v6.5.0
        if: always()
        with:
          report_paths: 'target/coverage/junit.xml'
